name = "tasks-app-backend-api-hono"
compatibility_date = "2024-04-13"

kv_namespaces = [
  { binding = "TASKS", id = "" },
  { binding = "COMMENTS", id = "" },
  { binding = "API_KEYS", id = "" }
]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"